name: "test-hello-ruby"
description: "some test description"
author: "jainpunit786@gmail.comk"
branding:
  icon: code
  color: red
runs:
  using: 'composite'
  steps:
    - run: |
        bundle exec ruby run.rb
      shell: bash
